cc_library(
        name = "dynamic_programming",
        hdrs = ["dynamic_programming.hpp"],
        srcs = ["dynamic_programming.cpp"],
        deps = [
                "//starobservationschedulingsolver/flexiblesinglenightstarobservationscheduling:flexiblesinglenightstarobservationschedulingsolver",
        ],
        visibility = ["//visibility:public"],
)
