cc_library(
        name = "dynamic_programming",
        hdrs = ["dynamic_programming.hpp"],
        srcs = ["dynamic_programming.cpp"],
        deps = [
                "//starobservationschedulingsolver/flexible_single_night_star_observation_scheduling:flexible_single_night_star_observation_scheduling",
        ],
        visibility = ["//visibility:public"],
)
