name: Build

on: [push]

jobs:

  build:
  
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8"]

    steps:
    - name: Checkout code
      uses: nschloe/action-cached-lfs-checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Download data
      run: |
        python3 -m pip install gdown
        gdown 1RzBH4LWSqHGdE-0SIpZZCluV6MLZ6b4f
        gdown 1ag21EFO0VzZlUccjTSVJ9tlT0uh7DbkS
        7z x star_observation_scheduling.7z -odata
        7z x flexible_star_observation_scheduling.7z -odata
    - name: Build Linux
      run: bazel build -- //...
      if: matrix.os != 'windows-latest'
    - name: Build Windows
      run: bazel build  --cxxopt=/MT -- //...
      if: matrix.os == 'windows-latest'
    - name: Run tests
      run: python3 scripts/tests_run.py test_results
    - name: Checkout main branch
      run: git checkout main
    - name: Build Linux
      run: bazel build -- //...
      if: matrix.os != 'windows-latest'
    - name: Build Windows
      run: bazel build  --cxxopt=/MT -- //...
      if: matrix.os == 'windows-latest'
    - name: Run tests
      run: python3 scripts/tests_run.py test_results_ref
    - name: Process tests
      run: python3 ./bazel-starobservationschedulingsolver/external/optimizationtools/scripts/tests_process.py --ref test_results_ref --new test_results
